theme = "cygnus"

[editor]
bufferline = "multiple"
end-of-line-diagnostics = "hint"
rainbow-brackets = true
completion-replace = true

[editor.cursor-shape]
insert="bar"

[editor.file-picker]
hidden = false

[editor.inline-diagnostics]
cursor-line = "warning" # show warnings and errors on the cursorline inline

[editor.statusline]
mode.normal = "âš¡ï¸"
mode.insert = "ðŸ–‹ï¸"
mode.select = "ðŸ”Ž"
center      = ["version-control"]
right       = ["diagnostics", "selections", "register", "position", "total-line-numbers", "file-encoding"]

[editor.lsp]
auto-signature-help = false
snippets = true
display-messages = true

[keys.normal]
# Print Git show for current line
space.B = """:echo \
%sh{git show -s --format='%%h {%%an|%%ad}: %%s' --date=format:'%%d-%%m-%%Y' \
$(git blame -p %{buffer_name} -L%{cursor_line},+1 | head -1 | cut -d' ' -f1)}
"""
C-t = "command_mode"
C-r = ":config-reload"
C-S-w = ":set whitespace.render all"
C-p = ":sh echo %{buffer_name} | pbcopy"
# Lazygit setup
C-g = [
    ":write-all",
    ":insert-output lazygit >/dev/tty",
    ":redraw",
    ":reload-all"
]

[keys.normal."["]
b = "goto_previous_buffer"
B = "goto_next_buffer"


[keys.normal."]"]
b = "goto_next_buffer"
B = "goto_previous_buffer"

[keys.normal.space.l]
c = "switch_to_lowercase"
C = "switch_to_uppercase"

[keys.insert]
C-p = "signature_help"
C-c = "normal_mode"
